services:
  echo-service:
    image: echo-service-example
    environment:
      - HOST=0.0.0.0
      - PORT=8080
    ports:
      - "8001:8080"
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      update_config:
        parallelism: 1
        order: start-first
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/health || exit 1"]
      interval: 5s
      timeout: 2s
      retries: 3
  frontend:
    image: frontend-example
    ports:
      - "3000:80"
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      update_config:
        parallelism: 1
        order: start-first
